//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiTechDistributionApp.BLL.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.OrdersDetails = new HashSet<OrdersDetail>();
            this.Authors = new HashSet<Author>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public decimal ISBN { get; set; }
        public decimal UnitPrice { get; set; }
        public int PublicationYear { get; set; }
        public int PublisherID { get; set; }
        public int QuantityAvailable { get; set; }
        public int CategoryID { get; set; }
    
        public virtual BooksCategory BooksCategory { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
    }
}
